### ISSUE TITLE
Default response on https://http2katanatest.cloudapp.net:8443/ is 404

### ISSUE THREAD

**Issue by akalin-chromium** [microsoftarchive/http2-katana#12]
I suggest something more festive! Perhaps this for `index.html`:

`<!doctype html>
<html>
<head><title>HTTP/2 test page</title></head>
<body>
  <h1>HTTP/2 is working!</h1>
  <image src="partytime.gif"></script>
  <h1>Yaay!!</h1>
</body>
</html>`

with `partytime.gif` being the image below:

![partytime](https://f.cloud.github.com/assets/3744200/906714/ebbd3506-fcd0-11e2-99ff-b163b852fff8.gif)

**Comment by jeffmendoza** [comment]
Awesome, Here are some things that may work in the meantime:

```
10mbTest.txt
Chalkboard HTML5 Benchmark.htm
index.html
Lite Brite Browser Performance Benchmark.htm
LookAround.htm
test.txt
```
