### ISSUE TITLE
Response headers erroneously has END_STREAM flag set

### ISSUE THREAD

**Issue by akalin-chromium** [microsoftarchive/http2-katana#13]
Since there's a response body, it shouldn't have the END_STREAM flag set

Here's the raw frame:

`00 11 01 0C 00 00 00 01 00 00 00 03 40 07 3A 73 74 61 74 75 73 03 34 30 34`

which translates into length=17, type=HEADERS, flags=END_STREAM(0x01) | END_HEADERS(0x04) | PRIORITY(0x08), etc.

**Comment by mcmanus** [comment]
wait, 00 11 01 0c is len=17 type=headers, flags=END_HEADERS | PRIORITY, right? (c is 12.. 8 | 4)

at least the frame header lgtm

**Comment by akalin-chromium** [comment]
Hunh, my mistake. Looks like the response header is fine.
