### ISSUE TITLE
Erroneous compressed header block for 2nd and subsequent responses

### ISSUE THREAD

**Issue by akalin-chromium** [microsoftarchive/http2-katana#15]
The first header block has:

`0x40 (Literal header with incremental indexing, no name matched) (7, ":status":) (3, "404")`

The working set for responses is then `{ 35, ":status", "404" }` (since there are 34 pre-existing entries in the response table).

Therefore, for subsequent 404s, the compressed header block should be empty (due to differential encoding).

However, I get:

`0xa6`,

which is an indexed header with index 38. So this is wrong because it's not differential encoding, and also because it appears that the server is erroneously using the request table (which has 37 pre-existing entries).

Looking at the source briefly, it looks like the stream ID is determining which header table to use, but it should be whether it's a request/response.

**Comment by jeffmendoza** [comment]
I've updated the server to hopefully do differential encoding.

**Comment by akalin-chromium** [comment]
Now the first HEADERS frame I receive has a header with an empty name.

I get `00 05 01 04 00 00 00 01 00 00 00 00 80`, which has a payload of `00 00 00 00 80`, which means 'literal header with substitution indexing and zero index' (first byte), then a zero-length header name (second byte), then a bunch of other stuff.

**Comment by jeffmendoza** [comment]
Looks like we had a bug with the latest priority fix. It was sizing for it, but not including it. I deployed a fix.

**Comment by squirrelfm** [comment]
seems to work

**Comment by akalin-chromium** [comment]
I can't really test this due to #18.

**Comment by akalin-chromium** [comment]
Looks like it's working now!
