### ISSUE TITLE
Incorrect comment/reference in SharedProtocol.Compression.Http2DeltaHeadersCompression

### ISSUE THREAD

**Issue by brianraymor** [microsoftarchive/http2-katana#16]
The implementation is based on draft-ietf-httpbis-header-compression-01 not:

namespace SharedProtocol.Compression.Http2DeltaHeadersCompression
{
    //This headers compression algorithm is described in
    // https://github.com/yoavnir/compression-spec/blob/7f67f0dbecdbe65bc22f3e3b57e2d5adefeb08dd/compression-spec.txt
    /// <summary>

    /// This class implement header compression.

**Comment by jeffmendoza** [comment]
Fixed
