### ISSUE TITLE
frame too large

### ISSUE THREAD

**Issue by mcmanus** [microsoftarchive/http2-katana#23]
https://http2katanatest.cloudapp.net:8443/test.txt

the first data frame header returned for that URI is
 FF FF 00 00 00 00 00 01

That is length 65535. So Firefox generates a session error because it is larger than allowed by spec.

The max allowable siz e is 16383 for HTTP (section 9.1). It is set that way to ensure responsiveness to priority information.

**Comment by squirrelfm** [comment]
Set to 16383 bytes according to latest spec.
