### ISSUE TITLE
Pick HTTP 2.0 as default protocol instead of HTTP 1.1

### ISSUE THREAD

**Issue by panarasi** [microsoftarchive/http2-katana#4]
If the list of advertised protocols includes both http/1.1 and HTTP-draft-04/2.0, http/1.1 is picked by the server. I worked around this by removing http/1.1 from Chrome's list, but ideally the server would pick 2.0, as Chrome sends the same list to all servers.

[Reported by Fred Akalin]

**Comment by brianraymor** [comment]
The server should prefer http/2 over http/1.1 if both are advertised by the client.

3.1.  The Application Layer Protocol Negotiation Extension

```
     …
```

   "ProtocolNameList" contains the list of protocols advertised by the
   client, in descending order of preference.

3.2.  Protocol Selection

   It is expected that a server will have a list of protocols that it
   supports, in preference order, and will only select a protocol if the
   client supports it.  In that case, the server SHOULD select the most
   highly preferred protocol it supports which is also advertised by the
   client.  In the event that the server supports no protocols that the
   client advertises, then the server SHALL respond with a fatal
   "no_application_protocol" alert.

**Comment by akalin-chromium** [comment]
Ah, I see. I guess there's a Chrome-side bug here, too, where we're advertising protocols in reverse preference order (d'oh!).

**Comment by akalin-chromium** [comment]
Chrome-side bug: https://code.google.com/p/chromium/issues/detail?id=267858

**Comment by jeffmendoza** [comment]
Igor has updated the code to use the server's priority, instead of taking priority from the client's list. And also for the server to prefer 2.0.
