### ISSUE TITLE
Protocol. Data received in wrong order

### ISSUE THREAD

**Issue by sgrebnov** [microsoftarchive/http2-katana#40]
Sometimes client receives data in different order from it was sent. We can have incorrect data received or even wrong frames for processing as a result.

Repro steps:
1) Start static files sample server
2) Start test client
3) Make one or more requests to get 10mbTest.txt file.

Expected: all requests complete successful.
Actual: some downloads fail or downloaded files are different from sent ones

**Comment by squirrelfm** [comment]
Fixed, closing
