### ISSUE TITLE
Initial header table is not updated to HPACK draft-03

### ISSUE THREAD

**Issue by tatsuhiro-t** [microsoftarchive/http2-katana#47]
Although README claims that http2-katana implements HPACK draft-03, the initial header table seems to be out of date.

http://tools.ietf.org/html/draft-ietf-httpbis-header-compression-03#appendix-B

**Comment by squirrelfm** [comment]
Fixed by 11c078c04a2bd5d17e1baa26ad7cefe53ad9ef23
