### ISSUE TITLE
Check upgrade string for 1.1 upgrade

### ISSUE THREAD

**Issue by jeffmendoza** [microsoftarchive/http2-katana#48]
src/Microsoft.Http2.Owin.Server/Adapters/Http11OwinMessageHandler.cs L164

Looks like we should be checking the upgrade string here (or somewhere else). We should only accept upgrade if it matches our protocol string (HTTP-draft-06/2.0).

**Comment by sgrebnov** [comment]
Right now we check this here
https://github.com/MSOpenTech/http2-katana/blob/master/src/Microsoft.Http2.Owin.Middleware/Http2Middleware.cs#L88

**Comment by jeffmendoza** [comment]
Ah, thanks. Lets change to check for the Procools.Http2 string, instead of 'HTTP' and '2.0'

**Comment by squirrelfm** [comment]
Check updated. Closing.
