### ISSUE TITLE
Correct certificate for hosted endpoint

### ISSUE THREAD

**Issue by panarasi** [microsoftarchive/http2-katana#5]
The certificate for https://http2katanatest.cloudapp.net:8443/ is for "localhost". It's also self-signed, but I can work around that by importing it. However, I can't think of a way to work around the hostname mismatch. Could the cert be updated to have the right hostname? I can bypass the interstitial in Chrome proper, but it's a bit more difficult to do so from fetch_client (the command-line client in the Chromium code base).

[Reported by Fred Akalin]

**Comment by jeffmendoza** [comment]
Fixed, according to Igor:

> > Replaced with self-signed wildcard cert for *.cloudapp.net
