### ISSUE TITLE
Send correct frame when tearing down connection

### ISSUE THREAD

**Issue by panarasi** [microsoftarchive/http2-katana#6]
The spec ( https://tools.ietf.org/html/draft-ietf-httpbis-http2-04#section-4.3 ) says that:

```
A receiver MUST
   terminate the connection with a connection error (Section 5.4.1) of
   type COMPRESSION_ERROR, if it does not decompress a header block.

```

(i.e., send a GOAWAY frame with COMPRESSION_ERROR before tearing down the connection). It would be nice to have the regular HTTP/2 endpoint send this frame before closing the connection so that it's easy to see whether it's being closed because of a compression error or something else.

**Comment by jeffmendoza** [comment]
According to Igor:

> > Will send COMPRESSION_ERROR. This not always will work since server may decompress header, but do that incorrectly and then fail later although problem was in compression.

Leaving open for now.

**Comment by squirrelfm** [comment]
Should be fixed
