### ISSUE TITLE
test server seems to be down

### ISSUE THREAD

**Issue by FabianFrank** [microsoftarchive/http2-katana#67]
$ telnet http2katanatest.cloudapp.net 8443
Trying 168.63.18.174...
...

No chance to connect.

**Comment by FabianFrank** [comment]
To provide more context: We are currently are in the progress of adding http2, NPN and ALPN support into libcurl. We would like to test our ALPN implementation (via OpenSSL and GnuTLS) against http2-katana if possible.

**Comment by ilyagalahov** [comment]
Endpoints restarted

**Comment by FabianFrank** [comment]
Thanks @ilyagalahov, it seems to be somewhat up now. I am still having problems with Firefox, however. I'm using the nightly channel with HTTP-draft-09/2.0 enabled. Twitter.com works fine and I can see in the developer console that it's using HTTP/2.0. Does it work for you? It looks to me as if http://http2katanatest.cloudapp.net:8080/root/index.html uses HTTP/1.1 and https://http2katanatest.cloudapp.net:8443/root/index.html hangs when trying to connect.

**Comment by ilyagalahov** [comment]
Could you try again, please. https://http2katanatest.cloudapp.net:8443/root/LookAround.htm and http://http2katanatest.cloudapp.net:8080/root/LookAround.htm are working for me with mozilla.

**Comment by FabianFrank** [comment]
Great! It works now, I can see that https://http2katanatest.cloudapp.net:8443/root/LookAround.htm is delivered via HTTP-draft-09/2.0.

**Comment by ilyagalahov** [comment]
Ok. closing it.
