### ISSUE TITLE
Investigate connection issue w/ Firefox

### ISSUE THREAD

**Issue by jeffmendoza** [microsoftarchive/http2-katana#8]
Patrick McManus reports:

So the pattern I'm seeing now is that we negotiate ALPN ok and then I send the connection magic followed by a settings, a window update (stream 0), a headers frame (stream 1), and a window_update (end flow control stream 1).. and I don't hear anything from the server at all for a few miliseconds and then the server hangs up on me. I don't receive any HTTP2 data at all.
I'll put the wireshark dump below. I can repeat this in a coordinated fashion with Brian so you can watch the logs or whatever too.. I've gone through the cap a couple of times and it seems legitimate to me 

This is my annotated log::

50 52 49 20 2a 20 48 54  54 50 2f 32 2e 30 0d 0a
0d 0a 53 4d 0d 0a 0d 0a
^^ connection magic

00 08 04 00 00 00 00 00
00 00 00 07 00 01 00 00
^^ settings iw 64KB

00 04 09 00 00 00 00 00
0f ff 00 01  
^^ update session window by 0x0fff0001.. now 0x10000000

-- START HEADERS FRAME --
00 c1 01 0d 00 00 00 01
^^ HEADERS FRAME.. len 0xc1, stream=1 flags=endhead,endstream,pri

00 00 0f f6
^^ priority = 0xff6

84
literal 4 [[ :method GET ]]

83
literal 3 [[ :path / ]]
43
indexed literal 2 [[ :host ]]
21
len 33(decimal)
68 74 74 70 32 6b 61 74  61 6e 61 74 65 73 74 2e
63 6c 6f 75 64 61 70 70  2e 6e 65 74 3a 38 34 34
33
[[ http2katanatest.cloudapp.net:8443 ]]
81
literal 1 [[ :scheme https ]]
4d
indexed literal 12 [[ user-agent ]]
44
len 68
4d 6f 7a 69 6c 6c 61 2f  35 2e 30 20
28 58 31 31 3b 20 4c 69  6e 75 78 20 78 38 36 5f
36 34 3b 20 72 76 3a 32  35 2e 30 29 20 47 65 63
6b 6f 2f 32 30 31 33 30  37 33 31 20 46 69 72 65
66 6f 78 2f 32 35 2e 30
[[ Mozilla/5.0 (X11; Linux x86_64; rv:25.0) Gecko/20130731 Firefox/25.0 ]]
46
indexed literal 5 [[ accept ]]
3f
len 63
74 65 78 74 2f 68
74 6d 6c 2c 61 70 70 6c  69 63 61 74 69 6f 6e 2f
78 68 74 6d 6c 2b 78 6d  6c 2c 61 70 70 6c 69 63
61 74 69 6f 6e 2f 78 6d  6c 3b 71 3d 30 2e 39 2c
2a 2f 2a 3b 71 3d 30 2e  38
[[ text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8 ]]
49
indexed literal 8 [[ accept-language ]]
0e
len 14
65 6e 2d 55 53
2c 65 6e 3b 71 3d 30 2e 35 
[[ en-US,en;q=0.5 ]]
--END OF HEADERS FRAME--

00 04 09 01 00 00 00 01 00 00 00 00  
^^window update stream id 1 - end flow control

[I read the fin from the server here]
00 08 07 00 00 00 00 00  00 00 00 00 00 00 00 00
^^ goaway and send fin
And this is the same log, but un-annotated:

50 52 49 20 2a 20 48 54  54 50 2f 32 2e 30 0d 0a
0d 0a 53 4d 0d 0a 0d 0a  00 08 04 00 00 00 00 00
00 00 00 07 00 01 00 00  00 04 09 00 00 00 00 00
0f ff 00 01  
00 c1 01 0d 00 00 00 01  00 00 0f f6 84 83 43 21
68 74 74 70 32 6b 61 74  61 6e 61 74 65 73 74 2e
63 6c 6f 75 64 61 70 70  2e 6e 65 74 3a 38 34 34
33 81 4d 44 4d 6f 7a 69  6c 6c 61 2f 35 2e 30 20
28 58 31 31 3b 20 4c 69  6e 75 78 20 78 38 36 5f
36 34 3b 20 72 76 3a 32  35 2e 30 29 20 47 65 63
6b 6f 2f 32 30 31 33 30  37 33 31 20 46 69 72 65
66 6f 78 2f 32 35 2e 30  46 3f 74 65 78 74 2f 68
74 6d 6c 2c 61 70 70 6c  69 63 61 74 69 6f 6e 2f
78 68 74 6d 6c 2b 78 6d  6c 2c 61 70 70 6c 69 63
61 74 69 6f 6e 2f 78 6d  6c 3b 71 3d 30 2e 39 2c
2a 2f 2a 3b 71 3d 30 2e  38 49 0e 65 6e 2d 55 53
2c 65 6e 3b 71 3d 30 2e  35 00 04 09 01 00 00 00
01 00 00 00 00  
00 08 07 00 00 00 00 00  00 00 00 00 00 00 00 00

**Comment by jeffmendoza** [comment]
Igor reports that we were incorrectly expecting the WINDOW_UPDATE  frame to be 16 bytes instead of 12. He fixed this and updated the endpoint.

Next, we need Patrick to test.

**Comment by jeffmendoza** [comment]
Our client connection header was wrong, fixed and redeployed.

**Comment by mcmanus** [comment]
Jeff - Progress! thanks!

I'm subscribed to the github issue, but I'll reply here cause attachments are a pain over there.

I now see data from the server.. a valid settings frame as the first thing, and then a 355 byte data frame with the end stream flag. The payload contains html with a not found message.

The problem is that I expect to see a headers frame with :status, etc.. so firefox resets the stream with PROTOCOL_ERROR due to an invalid state transition. Let me know what you think of that interpretation.

I ran the test at almost exactly midnight west coast time fri/sat (its morning here in berlin), and I'll attach the packet capture and premaster secret log so wireshark can decode it again.

**Comment by jeffmendoza** [comment]
Right, there should be headers. I'll let you know when we have an update.

From 8.1.3:

```
  The response MUST contain exactly one :status header field with
  exactly one response status value.  If the client receives an HTTP
  response that does not include the :status field, or provides
  multiple response status code values, it MUST respond with a
  stream error (Section 5.4.2) of type PROTOCOL_ERROR.
```

**Comment by jeffmendoza** [comment]
We are now sending a headers frame with only a :status before the data on response.

**Comment by jeffmendoza** [comment]
Going to close this one since we've made progress past this point, and have logged specific issues for where we are now.
